const metrics=[['followers','Followers'],['netFollowersGain','Net followers gain'],['interactions','Interactions'],['viewers','Viewers'],['profileVisits','Profile visits'],['bioLinkTaps','Bio link taps'],['likes','Likes'],['comments','Comments'],['shares','Shares'],['saves','Saves']];
const kpiMetrics=metrics.map(m=>m[0]);
const colors={followers:'#ff6b35',netFollowersGain:'#2faa68',interactions:'#8857d9',viewers:'#3976ed',profileVisits:'#19a6a0',bioLinkTaps:'#e8ac23',likes:'#e95789',comments:'#e95789',shares:'#3976ed',saves:'#8857d9'};
const $=id=>document.getElementById(id); const today=new Date();
let startDate=new Date(today); startDate.setDate(today.getDate()-13);
let rows=Array.from({length:14},(_,i)=>({date:formatDate(addDays(startDate,i))}));
const fmt=n=>Number(n||0).toLocaleString('en-IN');
function formatDate(d){return d.toISOString().slice(0,10)} function addDays(d,n){const x=new Date(d);x.setDate(x.getDate()+n);return x}
function pct(a,b){if(!a)return null;return((b-a)/a)*100} function sign(n){return n>0?'+':''}
function save(){localStorage.setItem('cultstoreInstagram14',JSON.stringify({rows}));$('saveStatus').textContent='Saved just now';setTimeout(()=>$('saveStatus').textContent='Saved in this browser',1200)}
function renderTable(){let h='<thead><tr><th>Date</th>'+metrics.map(m=>`<th>${m[1]}</th>`).join('')+'</tr></thead><tbody>';rows.forEach((r,i)=>{h+=`<tr><td><input data-i="${i}" data-key="date" type="date" value="${r.date||''}"></td>`+metrics.map(([key])=>`<td><input data-i="${i}" data-key="${key}" type="number" min="0" step="1" value="${r[key]??''}" placeholder="0"></td>`).join('')+'</tr>'});$('dataTable').innerHTML=h+'</tbody>';document.querySelectorAll('#dataTable input').forEach(input=>input.addEventListener('input',e=>{const {i,key}=e.target.dataset;rows[i][key]=key==='date'?e.target.value:Math.max(0,Number(e.target.value||0));save();renderAll()}))}
function total(key,a=0,b=14){return rows.slice(a,b).reduce((s,r)=>s+Number(r[key]||0),0)}
function renderKpis(){ $('kpis').innerHTML=kpiMetrics.map(key=>{const label=metrics.find(m=>m[0]===key)[1], value=total(key), change=pct(total(key,0,7),total(key,7,14)); return `<div class="kpi card"><div class="label">${label} · 14 days</div><div class="value">${fmt(value)}</div><div class="change ${change===null?'neutral':change>=0?'up':'down'}">${change===null?'Add both weeks':`${sign(change.toFixed(1))}${change.toFixed(1)}% vs first 7 days`}</div></div>`}).join('') }
function renderGrowth(){ $('growthGrid').innerHTML=kpiMetrics.map(key=>{const label=metrics.find(m=>m[0]===key)[1],a=total(key,0,7),b=total(key,7,14),change=pct(a,b);return `<div class="growth-item"><div class="label">${label}</div><div class="value ${change===null?'neutral':change>=0?'up':'down'}">${change===null?'—':`${sign(change.toFixed(1))}${change.toFixed(1)}%`}</div><div class="muted">${fmt(a)} → ${fmt(b)}</div></div>`}).join('')}
function drawChart(id,keys){const c=$(id),ctx=c.getContext('2d'),dpr=devicePixelRatio||1,w=c.clientWidth,h=290;c.width=w*dpr;c.height=h*dpr;ctx.scale(dpr,dpr);ctx.clearRect(0,0,w,h);const pad={l:38,r:12,t:16,b:30}, all=keys.flatMap(k=>rows.map(r=>Number(r[k]||0))), max=Math.max(...all,1), plotW=w-pad.l-pad.r,plotH=h-pad.t-pad.b;ctx.font='11px system-ui';ctx.fillStyle='#aaa';ctx.strokeStyle='#eee';ctx.lineWidth=1;for(let i=0;i<=4;i++){const y=pad.t+plotH*i/4;ctx.beginPath();ctx.moveTo(pad.l,y);ctx.lineTo(w-pad.r,y);ctx.stroke();ctx.fillText(fmt(Math.round(max*(1-i/4))),2,y+4)}rows.forEach((r,i)=>{if(i%2===0){ctx.fillStyle='#999';ctx.fillText((r.date||'').slice(5),pad.l+plotW*i/13-11,h-8)}});keys.forEach(key=>{ctx.strokeStyle=colors[key];ctx.lineWidth=2.5;ctx.beginPath();rows.forEach((r,i)=>{const x=pad.l+plotW*i/13,y=pad.t+plotH-(Number(r[key]||0)/max)*plotH;i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke();rows.forEach((r,i)=>{const x=pad.l+plotW*i/13,y=pad.t+plotH-(Number(r[key]||0)/max)*plotH;ctx.fillStyle=colors[key];ctx.beginPath();ctx.arc(x,y,3,0,Math.PI*2);ctx.fill()})})}
function renderAll(){renderTable();renderKpis();renderGrowth();drawChart('audienceChart',['viewers','followers','netFollowersGain']);drawChart('engagementChart',['interactions','likes','comments','shares','saves'])}
function sample(){rows=Array.from({length:14},(_,i)=>{const d={date:formatDate(addDays(startDate,i))};const factor=1+i*.08;metrics.forEach(([key],j)=>d[key]=Math.round((j+2)*120*factor+(i%3)*30));return d});save();renderAll()}
function csv(){const head=['date',...metrics.map(m=>m[0])];return [head,...rows.map(r=>head.map(k=>r[k]??''))].map(x=>x.join(',')).join('\n')}
function download(){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv()],{type:'text/csv'}));a.download='cultstore-instagram-14-day.csv';a.click()}
function importFile(file){const reader=new FileReader();reader.onload=()=>{const lines=reader.result.trim().split(/\r?\n/).map(x=>x.split(','));const heads=lines.shift().map(x=>x.trim());rows=lines.slice(0,14).map(line=>{const r={};heads.forEach((h,i)=>{if(h)r[h]=h==='date'?line[i]||'':Number(line[i]||0)});return r});while(rows.length<14)rows.push({date:formatDate(addDays(startDate,rows.length))});save();renderAll()};reader.readAsText(file)}
document.addEventListener('DOMContentLoaded',()=>{const saved=localStorage.getItem('cultstoreInstagram14');if(saved)try{rows=JSON.parse(saved).rows||rows}catch{};rows=rows.map(r=>{const n={date:r.date||''};metrics.forEach(([key])=>n[key]=Number(r[key]||0));return n});$('periodStart').value=rows[0]?.date||formatDate(startDate);$('periodStart').addEventListener('change',e=>{startDate=new Date(e.target.value+'T00:00:00');rows.forEach((r,i)=>r.date=formatDate(addDays(startDate,i)));save();renderAll()});$('loadSample').onclick=sample;$('exportCsv').onclick=download;$('importCsv').onchange=e=>e.target.files[0]&&importFile(e.target.files[0]);$('clearData').onclick=()=>{if(confirm('Clear all 14 days?')){rows=Array.from({length:14},(_,i)=>({date:formatDate(addDays(startDate,i))}));save();renderAll()}};window.addEventListener('resize',renderAll);renderAll()});
